#!/usr/bin/env bash
# Creates a narrow, least-privilege Postgres role + schema for one
# homelab-* app, inside the shared `homelab` database homelab-database
# itself creates. Never uses a stored/network admin credential -- always
# OS-level peer auth (`sudo -u postgres`), local or over SSH:
#
#   1. Local (--db-host is this host): `sudo -u postgres psql` directly.
#   2. Remote + SSH trust works: the identical bootstrap, piped through
#      `ssh <db-host> sudo -u postgres psql ...` instead of a local shell.
#   3. Neither works: the SQL is written to a file and printed for a
#      human to run by hand on the DB host; the caller is expected to
#      then just ask for the resulting role's password directly.
#
# On success, prints:
#   ROLE=<role>
#   PASSWORD=<password>
#   SCRAM_SECRET=<secret>
# SCRAM_SECRET is pulled straight from pg_authid.rolpassword (already in
# ready-to-use scram-secret format) -- callers that also register this
# role with homelab-pgbouncer's userlist.txt use it directly, no
# separate hashing step.
#
# Usage: bootstrap-app-role.sh --role NAME --schema NAME \
#            --schema-sql PATH --db-host HOST \
#            [--db homelab] [--password PASSWORD]
#
# --schema-sql is applied as-is (as the postgres superuser) and must
# create its own schema matching --schema (e.g.
# "CREATE SCHEMA IF NOT EXISTS myschema;"), which is then granted to
# --role afterward. This script does not create the schema itself
# first -- doing so would risk creating an empty schema disconnected
# from whatever name the SQL file actually hardcodes internally.
set -euo pipefail

DB=homelab
ROLE=""
SCHEMA=""
SCHEMA_SQL=""
DB_HOST=""
PASSWORD=""

SSH_OPTS=(-o BatchMode=yes -o ConnectTimeout=5 -o StrictHostKeyChecking=accept-new)
PENDING_DIR=/var/lib/homelab-database/pending

# log()/warn() always go to stderr: run_local()/run_remote()/run_manual()'s
# stdout is captured via command substitution to get the SCRAM secret, so
# anything printed to stdout inside them would corrupt that value.
log()  { echo "[bootstrap-app-role] $*" >&2; }
warn() { echo "[bootstrap-app-role] WARNING: $*" >&2; }
die()  { echo "[bootstrap-app-role] ERROR: $*" >&2; exit 1; }

while [ $# -gt 0 ]; do
    case "$1" in
        --role) ROLE="$2"; shift 2 ;;
        --schema) SCHEMA="$2"; shift 2 ;;
        --schema-sql) SCHEMA_SQL="$2"; shift 2 ;;
        --db-host) DB_HOST="$2"; shift 2 ;;
        --db) DB="$2"; shift 2 ;;
        --password) PASSWORD="$2"; shift 2 ;;
        *) die "unknown argument: $1" ;;
    esac
done

[ -n "$ROLE" ] || die "--role is required"
[ -n "$SCHEMA" ] || die "--schema is required"
[ -n "$SCHEMA_SQL" ] || die "--schema-sql is required"
[ -f "$SCHEMA_SQL" ] || die "--schema-sql file not found: $SCHEMA_SQL"
[ -n "$DB_HOST" ] || die "--db-host is required"
[ -n "$PASSWORD" ] || PASSWORD=$(openssl rand -base64 24)

is_local_host() {
    local host=$1
    case "$host" in
        localhost|127.0.0.1|::1) return 0 ;;
    esac
    [ "$host" = "$(hostname)" ] && return 0
    [ "$host" = "$(hostname -f 2>/dev/null || true)" ] && return 0
    return 1
}

sql_escape() { printf '%s' "$1" | sed "s/'/''/g"; }

build_sql() {
    local role_esc password_esc
    role_esc=$(sql_escape "$ROLE")
    password_esc=$(sql_escape "$PASSWORD")

    cat <<SQL
-- generated by homelab-database bootstrap-app-role.sh for role: $ROLE
DO \$\$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$role_esc') THEN
      CREATE ROLE "$ROLE" WITH LOGIN PASSWORD '$password_esc';
   ELSE
      ALTER ROLE "$ROLE" WITH LOGIN PASSWORD '$password_esc';
   END IF;
END
\$\$;

-- --schema-sql is expected to create its own schema (e.g.
-- "CREATE SCHEMA IF NOT EXISTS $SCHEMA;") -- it is applied as the
-- postgres superuser below, then granted to "$ROLE" afterward, rather
-- than this script creating the schema itself first: a schema created
-- here would be a separate, empty schema from whatever name the
-- caller's own SQL file hardcodes internally, silently splitting the
-- two. --schema must name the same schema the file itself creates.
SET search_path TO "$SCHEMA";

SQL
    cat "$SCHEMA_SQL"
    cat <<SQL

GRANT USAGE, CREATE ON SCHEMA "$SCHEMA" TO "$ROLE";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "$SCHEMA" TO "$ROLE";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "$SCHEMA" TO "$ROLE";
ALTER DEFAULT PRIVILEGES IN SCHEMA "$SCHEMA" GRANT ALL ON TABLES TO "$ROLE";
ALTER DEFAULT PRIVILEGES IN SCHEMA "$SCHEMA" GRANT ALL ON SEQUENCES TO "$ROLE";
SQL
}

print_scram_secret() {
    local psql_cmd=("$@")
    "${psql_cmd[@]}" -d "$DB" -X -tAc \
        "SELECT rolpassword FROM pg_authid WHERE rolname = '$(sql_escape "$ROLE")'"
}

run_local() {
    log "bootstrapping role '$ROLE' locally (db-host is this host)"
    # -q: suppress psql's own command-tag output (CREATE ROLE, DO, GRANT,
    # ...) -- this call's stdout feeds run_local()'s own stdout, which
    # main() captures via command substitution to get the SCRAM secret
    # below, so anything psql prints here would corrupt that value.
    if ! build_sql | sudo -u postgres psql -q -d "$DB" -X -v ON_ERROR_STOP=1; then
        return 1
    fi
    print_scram_secret sudo -u postgres psql
}

run_remote() {
    log "bootstrapping role '$ROLE' on $DB_HOST via SSH"
    if ! build_sql | ssh "${SSH_OPTS[@]}" "$DB_HOST" "sudo -u postgres psql -q -d $DB -X -v ON_ERROR_STOP=1"; then
        return 1
    fi
    ssh "${SSH_OPTS[@]}" "$DB_HOST" \
        "sudo -u postgres psql -d $DB -X -tAc \"SELECT rolpassword FROM pg_authid WHERE rolname = '$(sql_escape "$ROLE")'\""
}

ssh_trust_works() {
    ssh "${SSH_OPTS[@]}" "$DB_HOST" true >/dev/null 2>&1
}

run_manual() {
    mkdir -p "$PENDING_DIR"
    chmod 700 "$PENDING_DIR"
    local pending_file="$PENDING_DIR/${ROLE}-bootstrap.sql"
    build_sql > "$pending_file"
    chmod 600 "$pending_file"

    warn "cannot bootstrap '$ROLE' automatically (not local, and no SSH trust to $DB_HOST)"
    {
        echo
        echo "  On $DB_HOST, have an administrator run:"
        echo "    sudo -u postgres psql -d $DB -v ON_ERROR_STOP=1 -f $pending_file"
        echo "  (copy $pending_file to $DB_HOST first if it isn't already there)"
        echo
    } >&2

    local retry_choice
    while true; do
        if ! read -r -p "Press Enter once that's been run to fetch the role's secret (or 's' to skip): " retry_choice; then
            warn "no input available; skipping"
            return 1
        fi
        case "$retry_choice" in
            s|S) warn "skipping; re-run bootstrap-app-role.sh later to retry"; return 1 ;;
            *) ;;
        esac

        if is_local_host "$DB_HOST"; then
            if print_scram_secret sudo -u postgres psql; then
                return 0
            fi
        elif ssh_trust_works; then
            if ssh "${SSH_OPTS[@]}" "$DB_HOST" \
                    "sudo -u postgres psql -d $DB -X -tAc \"SELECT rolpassword FROM pg_authid WHERE rolname = '$(sql_escape "$ROLE")'\""; then
                return 0
            fi
        else
            warn "still no SSH trust to $DB_HOST; run the command above, then retry from a host that does"
        fi
    done
}

main() {
    local scram_secret
    if is_local_host "$DB_HOST"; then
        scram_secret=$(run_local) || die "local bootstrap failed"
    elif ssh_trust_works; then
        scram_secret=$(run_remote) || die "remote bootstrap over SSH failed"
    else
        scram_secret=$(run_manual) || die "bootstrap skipped"
    fi

    [ -n "$scram_secret" ] || die "role bootstrap reported success but no SCRAM secret was returned"

    echo "ROLE=$ROLE"
    echo "PASSWORD=$PASSWORD"
    echo "SCRAM_SECRET=$scram_secret"
}

main
